### ISSUE TITLE
Add clojure and css-in-js  to source alist

### ISSUE THREAD

**Issue by qingshuizheng** [renzmann/treesit-auto#1]
Hi Robb, just came from your post.
Thanks for the package, it works great.

Would you like to add these two to the source-alist? 😄 

```
(css-in-js "https://github.com/orzechowskid/tree-sitter-css-in-js")
(clojure "https://github.com/sogaiu/tree-sitter-clojure")
```

Thanks,
Zheng

**Comment by renzmann** [comment]
Absolutely! Feel free to submit a PR with the changes, in case you want the credit.  If not, I'll go ahead and add it

**Comment by qingshuizheng** [comment]
> If not, I'll go ahead and add it
Thanks Robb, Please go ahead and add it. 😄
