### ISSUE TITLE
None of the package functions show up when I install this package (either from VC or MELPA) under DOOM Emacs

### ISSUE THREAD

**Issue by alexispurslane** [renzmann/treesit-auto#105]
What the title says. If I do `M-x package-install` `treesit-auto`, it says it was successfully installed, but I get nothing. No `treesit-auto-install-all`, no `global-treesit-auto-mode`, nothing at all.

Here's my emacs information according to `doom info`:

```
generated  May 15, 2024 16:49:49
system     Fedora Linux 41 (Container Image Prerelease) Linux 6.8.8-300.fc40.x86_64 x86_64
emacs      29.3 EMACSDIR=~/.emacs.d/ EMACS=/usr/bin/emacs
doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master, origin/HEAD 9620bb4
	   2024-04-18 14:20:48 -0400 ~/.doom.d/
shell      /bin/bash
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF
	   LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG
	   RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM
	   XWIDGETS GTK3 ZLIB
traits     batch server-running custom-file
modules    :config use-package :completion company (vertico +icons) :ui doom doom-dashboard
	   (emoji +unicode) hl-todo ligatures modeline nav-flash ophints (popup +defaults)
	   treemacs unicode vc-gutter vi-tilde-fringe :editor (evil +everywhere) fold
	   (format +onsave) snippets word-wrap :emacs dired electric undo vc :checkers
	   syntax (spell +flyspell) grammar :tools debugger editorconfig (eval +overlay)
	   lookup (lsp +eglot) magit make pdf :lang (cc +lsp) common-lisp data emacs-lisp
	   json (javascript +lsp) (latex +fold +lsp) lua markdown (python +lsp +pyright) qt
	   (rust +lsp) sh web yaml :config (default +bindings +smartparens)
packages   (dtrt-indent) (paredit) (evil-numbers) (prettier) (writeroom-mode) (focus)
	   (eldoc-box) (treesit-auto)
elpa       treesit-auto
```

**Comment by renzmann** [comment]
It isn't clear from your description whether you're using one of the recommended [configurations](https://github.com/renzmann/treesit-auto?tab=readme-ov-file#configuration-example).  You're not seeing `global-treesit-auto-mode` even after using one of `use-package` or `require`?

**Comment by alexispurslane** [comment]
> It isn't clear from your description whether you're using one of the recommended [configurations](https://github.com/renzmann/treesit-auto?tab=readme-ov-file#configuration-example). You're not seeing `global-treesit-auto-mode` even after using one of `use-package` or `require`?

Doom Emacs has a custom package management solution that replaces both of those, which is what I was using — I had assumed that Doom's thing just did a use-package or a require under the hood, but apparently not, since once I did a use-package or require it worked just fine, as mentioned above lol. So this appears to be a doom specific thing. I resolve the problem by ceasing to use doom and writing my own vanilla emacs config from scratch lol

**Comment by trevarj** [comment]
>  You're not seeing global-treesit-auto-mode even after using one of use-package or require?

This is what I am now seeing on emacs 29.4. It only recently started happening and now I am investigating

**Comment by rafaeloledo** [comment]
@alexispurslane i think it's using straight, i've remeber reading in the README, i'm going to investigate it more and see on their docs
