### ISSUE TITLE
How to enable tree-sitter-elisp?

### ISSUE THREAD

**Issue by seagle0128** [renzmann/treesit-auto#19]
I noticed [`tree-sitter-elisp`](https://github.com/Wilfred/tree-sitter-elisp) can be installed via `treesit-install-lanaguge-grammer` with this package. But how to enable it? And I am wondering what's advantage of it. Thanks!

**Comment by renzmann** [comment]
Perhaps surprisingly, Emacs lisp is not one of the tree-sitter modes that will ship with Emacs 29 by default.  This is the full list so far:

```
js-ts-mode
c-ts-mode
yaml-ts-mode
tsx-ts-mode
css-ts-mode
csharp-ts-mode
dockerfile-ts-mode
bash-ts-mode
c-or-c++-ts-mode
ruby-ts-mode
java-ts-mode
python-ts-mode
toml-ts-mode
typescript-ts-mode
go-mod-ts-mode
cmake-ts-mode
c++-ts-mode
json-ts-mode
go-ts-mode
rust-ts-mode
```

For the grammar to take effect, we'd need something like `elisp-ts-mode` to be a part of that list.  I'm confident it will show up soon, but may require a third party package until it's a part of core Emacs

**Comment by renzmann** [comment]
Closing this for now, unless an `elisp-ts-mode` pops up
