### ISSUE TITLE
protobuf always Prompt download

### ISSUE THREAD

**Issue by donneyluck** [renzmann/treesit-auto#58]
https://github.com/abougouffa/minemacs/issues/114

**Comment by renzmann** [comment]
Looks like a simple error here: https://github.com/renzmann/treesit-auto/blob/bd7ba90f6084ab013f7703201eb3b59f260c9633/treesit-auto.el#L238

Based on the `grammar.js`, this should be `proto` instead of `protobuf`.   I'll patch this shortly.  Thanks for reporting!

**Comment by renzmann** [comment]
Fixed in [0.6.4](https://github.com/renzmann/treesit-auto/releases/tag/v0.6.4)
