### ISSUE TITLE
Can't get work for nix

### ISSUE THREAD

**Issue by anuvyklack** [renzmann/treesit-auto#66]
I am trying to add a recipe for nix language, but can't get it work. 
I use this configuration

```emacs-lisp
(use-package treesit-auto
  :ensure t
  :custom (treesit-auto-install t)
  :config
  (global-treesit-auto-mode)
  (add-to-list 'treesit-auto-langs 'nix)
  (add-to-list 'treesit-auto-recipe-list
               (make-treesit-auto-recipe
                :lang 'nix
                :ts-mode 'nix-ts-mode
                :remap 'nix-mode
                :url "https://github.com/nix-community/tree-sitter-nix"
                :revision "master"
                :source-dir "src"
                :ext "\\.nix\\'"))
  (treesit-auto-add-to-auto-mode-alist))
```

And when I manually call `treesit-auto-install-all` command, it builds
`libtree-sitter-nix.so`, but when I delete it, restart Emacs and visit Nix file,
nothing happens.

**Comment by renzmann** [comment]
> when I delete it, restart Emacs and visit Nix file, nothing happens

This would be because the default behavior of `treesit-auto-add-to-auto-mode-alist` is to only add tree-sitter modes that are *ready* to `auto-mode-alist`.  If you use `(treesit-auto-add-to-auto-mode-alist 'all)` or `(treesit-auto-add-to-auto-mode-alist '(nix))`, do you get the intended behavior?

**Comment by renzmann** [comment]
Additionally, feel free to contribute this recipe in a PR so we can just include nix with treesit-auto!
