### ISSUE TITLE
File mode specification error: (void-function markdown-ts-mode)

### ISSUE THREAD

**Issue by jdufresne** [renzmann/treesit-auto#69]
I have treesit-auto working for most languages, but opening a markdown file results in the following in my `*Messages*` buffer:

```
File mode specification error: (void-function markdown-ts-mode)
```

The markdown buffer then does not have syntax highlighting.

Is there a dependency that I must install alongside treesit-auto for markdown support?

I have configured treesit-auto with:

```elisp
(use-package treesit-auto
  :config (progn
            (setq treesit-auto-install t)
            (treesit-auto-add-to-auto-mode-alist 'all)
            (global-treesit-auto-mode)))
```

**Comment by renzmann** [comment]
Thanks for the bug report! Fixed in 1.0.1

**Comment by rien333** [comment]
Question: who or what is providing markdown-ts-mode?

**Comment by rien333** [comment]
> Please note that I don't have the markdown-mode installed ...  Is that the issue here?

No, I see the same thing, and I do have markdown-mode installed.
