### ISSUE TITLE
No prompt auto installation

### ISSUE THREAD

**Issue by dimicuss** [renzmann/treesit-auto#88]
After 1.0.2 -> 1.0.3, i suppose, prompting for grammar installation no longer works

**Comment by renzmann** [comment]
Did https://github.com/renzmann/treesit-auto/pull/85 fix this?  I just bumped it to 1.0.4 with this change.

**Comment by dimicuss** [comment]
> Did #85 fix this? I just bumped it to 1.0.4 with this change.

Thanks! All works properly!

**Comment by ChauhanT** [comment]
Hi, sorry to resurrect an old thread. I am using `straight` to install `treesit-auto` and do not see an auto installation prompt. Do I have to configure `eglot` before I call `treesit-auto`? Thank you!

**Comment by dimicuss** [comment]
> Hi, sorry to resurrect an old thread. I am using `straight` to install `treesit-auto` and do not see an auto installation prompt. Do I have to configure `eglot` before I call `treesit-auto`? Thank you!

I think problem in `straight`. Can you ensure from what repo he downloads packages?

**Comment by ChauhanT** [comment]
Hi @dimicuss, thanks. I think I figured it out. All hooks need to go to `*-ts-mode`s and not `*-mode`s !
